cmake_minimum_required(VERSION 3.22.1)
project(byqx)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libnode.so)
add_library(byqx-node SHARED src/main/cpp/node.cpp)
target_include_directories(byqx-node PRIVATE libnode/include/node)
target_link_options(byqx-node PRIVATE "-Wl,-z,max-page-size=16384")
target_link_libraries(byqx-node node log)
